### ISSUE TITLE
Unwrap the bean as a JS obj

### ISSUE THREAD

**Issue by Lokeh** [mfikes/cljs-bean#10]
For my use case, I want to provide a user of my library the ability to immutably update a JS object using the core library and then I _unwrap the object_ so that I can pass it to React.

Something akin to this:

```clojure
(defn Component [props]
  (let [cljs-props (bean props)
        cljs-props' (assoc cljs-props :foo "bar")]
    (react/createElement (unwrap cljs-props') "baz")))
```

AFAICT updates to the bean return a regular map so, for my use case, it just might not fit. What do you think, @mfikes ?

**Comment by mfikes** [comment]
Yeah, this seems like a reasonable extension to Clojure's `bean` semantics, given that JavaScript objects easily cloneable and malleable.

This could prove to be incredibly powerful. For example, here is using a transducer to create a JavaScript object:

```
cljs.user=> (into (bean #js {}) (filter (comp odd? val)) {:a 1, :b 2, :c 3})
{:a 1, :c 3}
cljs.user=> (object *1)
#js {:a 1, :c 3}
```

(If this pattern proves to be useful, then a 0-arity `(bean)` call might be convenient.)
