### ISSUE TITLE
Working With Arrays

### ISSUE THREAD

**Issue by dehli** [mfikes/cljs-bean#86]
Hi, thanks in advance for your help and this library!

I've got a question about the following code. Is this expected? If I were to change `->clj` to `(js->clj % :keywordize-keys true)` the code would pass. My understanding was that `->clj` should behave similarly to `js->clj`. 

Cheers!

```clj
{:deps {cljs-bean/cljs-bean {:mvn/version "1.7.0"}}
```

```clj
(deftest cljs-bean-test
  (let [clj-obj (->clj #js {:coll #js [#js {:id "foo"}]})]
    (is (= (conj (:coll clj-obj) {:id "bar"})
           [{:id "foo"} {:id "bar"}]))))

FAIL in (cljs-bean-test)
expected: (= (conj (:coll clj-obj) {:id "bar"}) [{:id "foo"} {:id "bar"}])
  actual: (not (= [#js {:id "foo"} {:id "bar"}] [{:id "foo"} {:id "bar"}]))

```

**Comment by drewverlee** [comment]
@dehli it migth be the case the test is failing because by default beans aren't recursive like js->clj. See https://github.com/mfikes/cljs-bean/blob/master/doc/recursive.md for more

**Comment by drewverlee** [comment]
Also, it would seem to behave the same way as js->clj

```
(let [clj-obj (->clj #js {:coll #js [#js {:id "foo"}]})]
  (= (conj (:coll clj-obj) {:id "bar"})
     [{:id "foo"} {:id "bar"}]));; => false

(let [clj-obj (js->clj #js {:coll #js [#js {:id "foo"}]})]
  (= (conj (:coll clj-obj) {:id "bar"})
     [{:id "foo"} {:id "bar"}]));; => false
```

Here is an interesting case, not an inner vector is a js object after we conj. 

```
(-> #js{:coll #js [#js {:id "foo"}]}
    ->clj
    :coll
    (conj #js{:id "bar"})
    );; => [#js {:id "foo"} #js {:id "bar"}]

```

So if we want to use it for an equality check we would need to do that at the equality check time I believe. Which would make sense with the idea of it being a wrapper and not a way to transform the data.

**Comment by dehli** [comment]
@drewverlee Thanks for the idea! Your specific example fails for a different reason. If you were to change your code to include `keywordize-keys true` (which `->clj` does by default) you'd see that it actually does pass. 

```clj
(let [clj-obj (js->clj #js {:coll #js [#js {:id "foo"}]} :keywordize-keys true)]
  (= (conj (:coll clj-obj) {:id "bar"})
     [{:id "foo"} {:id "bar"}]));; => true
```

**Comment by mfikes** [comment]
This is similar to #68 but for vectors. The solution implemented with #69 appears to have dealt with maps, but didn't fully deal with vectors.

Deeper explanation:

If you do something like

```clj
(conj (->clj #js [#js {:id "foo"}]) 1)
```

since the value being `conj`ed  is a primitive JavaScript value, `cljs-bean` returns an object that continues to wrap a JavaScript array, and can be converted to JavaScript in constant time.

But if instead you do

```
(conj (->clj #js [#js {:id "foo"}]) {:id "bar"})
```

this approach cannot be taken and, at this point, `cljs-bean` takes the strategy of converting the result to a ClojureScript data structure.

The defect here is that this conversion is currently not recursive (as it is with maps).

**Comment by dehli** [comment]
Thanks for the in-depth explanation and for the fix!

**Comment by mfikes** [comment]
@dehli Thanks for the great catch. That was an obscure bug! I think I'll let #87 sit for a while to soak and ensure it is correct.

**Comment by mfikes** [comment]
@drewverlee #87 fixes the interesting case you raised:

```clj
(-> #js{:coll #js [#js {:id "foo"}]}
    ->clj
    :coll
    (conj #js{:id "bar"})
    );; => [{:id "foo"} #js {:id "bar"}]
```
